#:kivy 1.0

ScrollView:
	size_hint_y: None
	FloatLayout:
		StackLayout:
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello from test.kv'
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello 2'
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello 3'
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello 4'
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello 5'
			Button:
				size_hint: [0.25,0.6]
				text: 'Hello 6'

